### ISSUE TITLE
Vylúčiť slová ≤ dva znaky

### ISSUE THREAD

**Issue by slavkoja** [jtomori/diceware_slovak#1]
Dovolím si písať v materčine, verím, že to nevadí ;-)

Myslím, že je potrebné buď vylúčiť jedno- a dvoj-znakové slová alebo opraviť informáciu o entropii (osobne som za vylúčenie). Problém je v tom, že naša abeceda má 46 písmen, čiže jeden znak má bitovú entropiu 5,52 a dva znaky teda 11,02 (oba zaokrúhlené) a túto entropiu budú mať aj jedno-slovné heslá s týmto počtom znakov a nie deklarovaných 12,92 (a už vôbec nie viac pri väčšom slovníku). Obdobný problém môže nastať aj pri viac-slovných heslách, zložených s týchto krátkych slov.

Prípadný útočník predsa nie je nijako nútený skúšať slová so slovníka, ale pokojne môže zvoliť bežnú hrubú silu. A tak je potrebné zvoliť minimálnu dĺžku slov tak, aby celkovú entropiu neznižovala, a to ani v tom najhoršom prípade.

Mimochodom, nie som matematický expert, len správca systému, tak sa môžem mýliť...

**Comment by jtomori** [comment]
Čau, diki za feedback.
Súhlasím, myslim si, že to dáva zmysel zohľadniť to, aby dĺžka slov nemala nižšiu entropiu (z pohľadu brute force), než na základe veľkosti slovníka.
Bude to jednoduchá zmena, stačí upraviť [`word_filter()`](https://github.com/jtomori/diceware_slovak/blob/master/generate.py#L6) tak, aby zohľadnila žiadanú entropiou. Bude ale treba tiež urobiť nejaký check / upozornenie aby výsledný slovník mal dostatočné množstvo slov - pre prípad, že he ten filter zníži.

Keď sa k tomu dostanem, tak to opravím :)

**Comment by slavkoja** [comment]
Som presvedčený, že na vylepšenie je toho viac.

Každopádne, po jednoduchej analýze dĺžky slov (awk), vylúčenie dvojznakových slov nijako neovplyvní žiadny zoznam -- je ich "málo". No v prípade dlhších slovníkov treba vylúčiť i troj, prípadne viac znakové slová, kde už problém nastať môže. Myslím, že treba tiež skrátiť hornú hranicu filtra, pretože neverím, že niekto bude písať šestnásť-znakové slová, max. tak desať a aj to je otázne ;-) Myslím, že osem-kockový slovník to vylučuje úplne a možno ho zavrhnúť. Dolná hranica by mala byť ešte prísnejšia, pretože mnoho týchto krátkych slov používa len znaky anglickej abecedy, čo ich entropiu ďalej znižuje, a tak môže byť problém aj so sedem-kockovým...

V neposlednom rade, slová by mali byť v základnom tvare a všetky malými písmenami. Použitie písmen s rôznou veľkosťou a slov v inom tvare ako je v slovníku, pridá dodatočnú entropiu, a tak môže stačiť päť- prípadne šesť-kockový slovník a trocha kreativity...

**Comment by slavkoja** [comment]
Prehnal som ``frequency_list.txt`` (po odstránení \r) cez stemmer z ``hunspell`` a vygeneroval som kompletné počítadlá (Counter) slov so slovenskými znakmi (dĺžka 3 - 7), bez slovenských znakov (4 - 7) a výsledok je:
```
 Sk+noSk       Sk     noSk 
   56277    35641    20636 
```
Takže so slovných základov s dĺžkou do 7 znakov možno bez problémov vygenerovať šesť-kockový zoznam, päť-kockový možno dokonca vygenerovať len zo slov so slovenskými znakmi s dĺžkou 3 - 6 znakov (18 917 slov).

**Comment by jtomori** [comment]
Will reply in English :)
In e3ca136aceb30a41 I fixed the issue with bruteforce based entropy being lower than dictionary based entropy: e.g. in the case of **7 dice rolls list** one word should have entropy of 18.1 bits, but the chosen word could be `na`, whose bruteforce entropy is definitely smaller (the exact number depends on the chosen alphabet). 
Now the **7 dice rolls list** will contain only words with at least 5 characters, which is larger or equal to the wordlist's entropy.

I also cleaned up a couple of things and removed foreign words from `frequency_list.txt` which would be hard to remember.

I added an option to specify an alphabet and discarded the **8 dice rolls list**, which now I don't have enough words for :)

I will close this issue for now. Feel free to re-open if you have more suggestions.
